=== AllenTsang/xml-lab/data/schedule.dtd
<!ELEMENT schedule (days, periods, courses)>
<!ATTLIST schedule 
	year CDATA #REQUIRED
	term CDATA #REQUIRED
	program CDATA #REQUIRED
	set CDATA #REQUIRED
>


<!ELEMENT days (day+)>
<!ELEMENT day (booking+)>
<!ATTLIST day
	daysOfTheWeek (mon|tue|wed|thu|fri|sat|sun) #REQUIRED
>


<!ELEMENT periods (timeslot+)>
<!ELEMENT timeslot (booking+)>
<!ATTLIST timeslot
	time (0830|0930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
>


<!ELEMENT courses (course+)>
<!ELEMENT course (booking+)>


<!ELEMENT booking (courseNumber, weekday, time, instructor, room)>
<!ATTLIST booking
	type (lab|lecture) #REQUIRED
>
<!ELEMENT courseNumber (#PCDATA)>
<!ELEMENT weekday (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT room (#PCDATA)>

=== AllenTsang/xml-lab/data/schedule.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM 'schedule.dtd'>

<schedule year="2016" term="Winter" program="CST" set="40">
	<days>
		<day daysOfTheWeek="mon">
			<booking type="lab">
				<courseNumber>COMP4985</courseNumber>
				<weekday>Monday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
			<booking type="lecture">
				<courseNumber>COMP4735</courseNumber>
				<weekday>Monday</weekday>
				<time>1130</time>
				<instructor>Mirela Gutica</instructor>
				<room>SW01-1205</room>
			</booking>
			<booking type="lab">
				<courseNumber>BLAW3600</courseNumber>
				<weekday>Monday</weekday>
				<time>1230</time>
				<instructor>Catherine Ryan</instructor>
				<room>SE09-127</room>
			</booking>
			<booking type="lab">
				<courseNumber>COMP4560</courseNumber>
				<weekday>Monday</weekday>
				<time>1530</time>
				<instructor>Joseph Lo</instructor>
				<room>SE12-320</room>
			</booking>
		</day>
	</days>
	<periods>
		<timeslot time="0930">
			<booking type="lab">
				<courseNumber>COMP4985</courseNumber>
				<weekday>Monday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
			<booking type="lab">
				<courseNumber>COMP4981</courseNumber>
				<weekday>Tuesday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
			<booking type="lab">
				<courseNumber>COMP4985</courseNumber>
				<weekday>Wednesday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
			<booking type="lab">
				<courseNumber>COMP4981</courseNumber>
				<weekday>Thursday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
			<booking type="lecture">
				<courseNumber>BLAW3600</courseNumber>
				<weekday>Friday</weekday>
				<time>0930</time>
				<instructor>Catherine Ryan</instructor>
				<room>SW05-1840</room>
			</booking>
		</timeslot>
	</periods>
	<courses>
		<course>
			<booking type="lab">
				<courseNumber>COMP4985</courseNumber>
				<weekday>Monday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
			<booking type="lab">
				<courseNumber>COMP4985</courseNumber>
				<weekday>Wednesday</weekday>
				<time>0930</time>
				<instructor>Aman Abdulla</instructor>
				<room>SE12-323</room>
			</booking>
		</course>
	</courses>
</schedule>
